import React, { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Tooltip } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Activity, ShieldAlert, Cpu, Layers, Maximize2, Minimize2, Settings, CloudLightning, Navigation, Calendar, ChevronDown, ChevronUp, Zap, Thermometer, Wind, Droplet, Download, Landmark } from 'lucide-react';
import clsx from 'clsx';

export default function App() {
    const [leadTime, setLeadTime] = useState(1);
    const [activeTab, setActiveTab] = useState('map');
    const [isLive, setIsLive] = useState(true);
    const [regionsData, setRegionsData] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    // HOMEPAGE STATE
    const [showDashboard, setShowDashboard] = useState(false);

    // NEW: Expandable Insight State
    const [expandedRegion, setExpandedRegion] = useState(null);

    const [isMapFullscreen, setIsMapFullscreen] = useState(false);

    const fetchForecast = async () => {
        setIsLoading(true);
        try {
            const response = await fetch(`http://127.0.0.1:8000/api/forecast?lead_time=${leadTime}`);
            const data = await response.json();
            setRegionsData(data);
            setIsLive(true);
        } catch (err) {
            console.error("API Error - Make sure Backend is running", err);
            setIsLive(false);
        }
        setIsLoading(false);
    };

    useEffect(() => {
        fetchForecast();
    }, [leadTime]);

    const getColor = (errorProb) => {
        if (errorProb > 70) return '#ef4444'; // Red
        if (errorProb > 40) return '#f59e0b'; // Amber
        return '#10b981'; // Emerald
    };

    const generateReport = () => {
        const critical = regionsData.filter(r => r.errorProb >= 50).sort((a, b) => b.errorProb - a.errorProb);
        const printWindow = window.open('', '', 'width=800,height=900');

        printWindow.document.write(`
            <html>
                <head>
                    <title>AeroBust_Emergency_Report_Day${leadTime}</title>
                    <style>
                        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; background: #fff; }
                        .header { text-align: center; border-bottom: 3px solid #ef4444; padding-bottom: 20px; margin-bottom: 30px; }
                        h1 { color: #ef4444; margin: 0; font-size: 28px; text-transform: uppercase; letter-spacing: 2px; }
                        .timestamp { font-size: 11px; color: #64748b; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; margin-top: 10px; }
                        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px;}
                        th, td { border: 1px solid #cbd5e1; padding: 12px; text-align: left; }
                        th { background: #f8fafc; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #475569; }
                        .risk-high { color: #ef4444; font-weight: bold; }
                        .insight { background: #fef2f2; border-left: 4px solid #ef4444; padding: 15px; margin-top: 15px; font-size: 13px; line-height: 1.5; color: #7f1d1d;}
                        .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px;}
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>OFFICIAL BUST WARNING REPORT</h1>
                        <p style="margin:5px 0 0 0; color:#475569; font-weight: bold;">DEPARTMENT OF ATMOSPHERIC INTELLIGENCE</p>
                        <div class="timestamp">Generated by AeroBust AI &bull; Target Day: T+${leadTime} &bull; ${new Date().toLocaleString()}</div>
                    </div>
                    
                    <h3 style="color:#0f172a; text-transform:uppercase; font-size:14px;">1. Critical Nodes Summary (Bust Probability > 50%)</h3>
                    ${critical.length > 0 ? `
                    <table>
                        <thead><tr><th>Location</th><th>Bust Probability</th><th>Causal Insight (LSTM)</th></tr></thead>
                        <tbody>
                            ${critical.map(c => `
                                <tr>
                                    <td style="font-weight:bold;">${c.name}<br/><span style="font-size:10px;color:#64748b;font-weight:normal;">Node ${c.id}</span></td>
                                    <td class="risk-high">${c.errorProb}% Deviation</td>
                                    <td>${c.explainability || 'Atmospheric processing...'}</td>
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                    ` : '<p style="color:#10b981; font-weight:bold; padding: 20px; background: #ecfdf5;">✔️ No critical anomalies detected for this timeline.</p>'}
                    
                    <h3 style="color:#0f172a; text-transform:uppercase; font-size:14px; margin-top:40px;">2. Sector Impact Advisory</h3>
                    ${critical.length > 0 ? `
                        <div class="insight">
                            <strong>AVIATION SECTOR:</strong> Ground highly volatile regions immediately. Prepare for unforecasted wind shears or heavy precipitation.<br/><br/>
                            <strong>AGRICULTURE SECTOR:</strong> Issue advisory against sowing/harvesting in affected nodes. NWP baseline is severely disjointed from atmospheric reality.
                        </div>
                    ` : '<p>All monitored sectors are nominal and clear for operations.</p>'}

                    <div class="footer">
                        RESTRICTED GOVT WORKSPACE &bull; AEROBUST AI AUTOMATED EXTN
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        setTimeout(() => printWindow.print(), 350);
    };

    if (!showDashboard) {
        return (
            <div className="flex min-h-screen w-screen bg-[#020617] text-white flex-col items-center justify-center relative overflow-hidden font-sans pb-10">
                {/* Enterprise Navbar */}
                <nav className="absolute top-0 w-full py-6 px-4 md:px-10 flex justify-between items-center z-50 animate-fade-in-up">
                    <div className="flex items-center gap-3">
                        <div className="p-0.5 bg-white rounded-full shadow-lg shadow-indigo-500/20 overflow-hidden flex items-center justify-center w-10 h-10 shrink-0 border-2 border-indigo-500/50">
                            <img src="/logos/images (2).jpg" alt="AeroBust Logo" className="w-full h-full object-contain mix-blend-multiply" />
                        </div>
                        <span className="text-xl font-bold tracking-widest uppercase bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent">AeroBust</span>
                    </div>
                    <div className="hidden md:flex gap-4 items-center">
                        {/* SIH Logo replacing text */}
                        <div className="h-10 px-4 bg-white rounded-xl shadow-lg shadow-indigo-500/10 flex items-center justify-center border-2 border-indigo-500/20 hover:scale-105 transition-transform">
                            <img src="/logos/images (3).jpg" alt="SIH 2026 Logo" className="h-full w-auto object-contain mix-blend-multiply" />
                        </div>
                        {/* Gov Emblem replacing Secured Node text */}
                        <div className="h-10 px-4 bg-gradient-to-r from-amber-900/20 to-slate-900 border border-amber-700/50 rounded-xl flex items-center justify-center shadow-[0_0_15px_rgba(217,119,6,0.15)] hover:border-amber-500/80 transition-colors">
                            <img src="/logos/Emblem_of_India_with_transparent_background.png" alt="Govt Emblem" className="h-7 w-auto object-contain drop-shadow-[0_0_8px_rgba(251,191,36,0.3)] brightness-125" />
                        </div>
                    </div>
                </nav>

                {/* Immersive Backgrounds */}
                <div className="absolute inset-0 bg-[linear-gradient(to_right,#4f4f4f15_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f15_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_40%,#000_70%,transparent_100%)] pointer-events-none"></div>
                <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-indigo-700/10 blur-[130px] rounded-full mix-blend-screen pointer-events-none"></div>
                <div className="absolute bottom-[-20%] right-[-10%] w-[60%] h-[60%] bg-blue-700/10 blur-[130px] rounded-full mix-blend-screen pointer-events-none"></div>

                <div className="relative z-10 text-center max-w-5xl px-4 md:px-6 flex flex-col items-center animate-fade-in-up w-full mt-24 md:mt-16">
                    <div className="inline-flex items-center gap-3 px-5 py-2 lg:py-2.5 rounded-full bg-slate-900/80 border border-indigo-500/30 mb-8 backdrop-blur-md shadow-[0_0_20px_rgba(99,102,241,0.15)] hover:border-indigo-500/60 transition-colors">
                        <span className="flex h-2 w-2 relative">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                        </span>
                        <span className="text-[9px] md:text-[11px] font-black tracking-[0.2em] text-emerald-400 uppercase">System Calibrated. Ready for Telemetry.</span>
                    </div>

                    <h1 className="text-5xl md:text-7xl lg:text-8xl font-black mb-6 tracking-tighter bg-gradient-to-br from-white via-slate-200 to-indigo-800/80 bg-clip-text text-transparent leading-[1.1] md:leading-[1.1]">
                        Weather specific. <br /> Not speculative.
                    </h1>
                    <p className="text-base md:text-lg lg:text-xl text-slate-400 mb-12 max-w-3xl font-medium leading-relaxed px-4 md:px-0">
                        An advanced neural network architecture that actively intercepts numerical weather prediction (NWP) models to detect forecast anomalies & busts before they impact infrastructure.
                    </p>

                    <button
                        onClick={() => setShowDashboard(true)}
                        className="group relative inline-flex items-center gap-4 px-8 py-4 md:px-12 md:py-5 bg-gradient-to-b from-indigo-500 to-indigo-700 hover:from-indigo-400 hover:to-indigo-600 text-white font-bold rounded-2xl transition-all duration-300 shadow-[0_0_40px_rgba(79,70,229,0.4)] hover:shadow-[0_0_60px_rgba(79,70,229,0.7)] hover:-translate-y-1 overflow-hidden border border-indigo-400/50"
                    >
                        <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-[shimmer_1.5s_infinite]"></span>
                        <span className="tracking-[0.1em] uppercase text-xs md:text-sm font-black">Get Started</span>
                        <Navigation size={20} className="group-hover:translate-x-1.5 group-hover:-translate-y-1.5 transition-transform" strokeWidth={2.5} />
                    </button>

                    {/* Feature Bento Cards */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-16 lg:mt-24 w-full animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
                        <div className="bg-slate-900/60 p-6 rounded-3xl border border-slate-800/80 backdrop-blur-xl flex flex-col items-center text-center group hover:bg-slate-800/80 transition-all hover:border-indigo-500/30">
                            <div className="p-3 bg-indigo-500/10 rounded-2xl mb-4 group-hover:scale-110 transition-transform shadow-inner border border-indigo-500/20">
                                <Cpu className="text-indigo-400" size={24} />
                            </div>
                            <h3 className="text-white font-bold text-sm mb-2 tracking-wide">ConvLSTM Neural Engine</h3>
                            <p className="text-[11px] text-slate-400 font-medium">Deep learning architecture parsing spatial-temporal atmospheric shifts and historic data grids.</p>
                        </div>
                        <div className="bg-slate-900/60 p-6 rounded-3xl border border-slate-800/80 backdrop-blur-xl flex flex-col items-center text-center group hover:bg-slate-800/80 transition-all hover:border-emerald-500/30">
                            <div className="p-3 bg-emerald-500/10 rounded-2xl mb-4 group-hover:scale-110 transition-transform shadow-inner border border-emerald-500/20">
                                <Activity className="text-emerald-400" size={24} />
                            </div>
                            <h3 className="text-white font-bold text-sm mb-2 tracking-wide">Explainable AI (XAI)</h3>
                            <p className="text-[11px] text-slate-400 font-medium">A causal generative matrix highlighting exactly why the forecast boundary is mathematically broken.</p>
                        </div>
                        <div className="bg-slate-900/60 p-6 rounded-3xl border border-slate-800/80 backdrop-blur-xl flex flex-col items-center text-center group hover:bg-slate-800/80 transition-all hover:border-blue-500/30">
                            <div className="p-3 bg-blue-500/10 rounded-2xl mb-4 group-hover:scale-110 transition-transform shadow-inner border border-blue-500/20">
                                <ShieldAlert className="text-blue-400" size={24} />
                            </div>
                            <h3 className="text-white font-bold text-sm mb-2 tracking-wide">Live IMD Telemetry</h3>
                            <p className="text-[11px] text-slate-400 font-medium">Real-time fusion of satellite observations continuously monitoring 50+ Pan-India nodes.</p>
                        </div>
                    </div>

                    {/* System Status Indicators */}
                    <div className="mt-10 flex gap-3 flex-wrap justify-center animate-fade-in-up" style={{ animationDelay: '0.6s' }}>
                        {['IMD Satellite Sync', 'Neural Diagnostics', 'Real-time Radar', 'Anomaly Detector', 'Govt Encrypted Node'].map(tech => (
                            <div key={tech} className="px-4 py-2 bg-slate-950/50 rounded-xl border border-slate-800/60 flex items-center gap-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest backdrop-blur-sm shadow-inner hover:border-slate-600 transition-colors cursor-default">
                                <div className="w-1.5 h-1.5 rounded-full bg-slate-600"></div>
                                {tech}
                            </div>
                        ))}
                    </div>

                    {/* Page Filling Overview Section */}
                    <div className="w-full mt-32 border-t border-slate-800/80 pt-24 pb-20 relative px-4 md:px-0 animate-fade-in-up" style={{ animationDelay: '0.8s' }}>
                        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-[1px] bg-gradient-to-r from-transparent via-indigo-500/50 to-transparent"></div>
                        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[300px] bg-indigo-600/10 blur-[100px] rounded-full pointer-events-none"></div>

                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 max-w-5xl mx-auto relative z-10 text-left">
                            {/* The Problem */}
                            <div className="flex flex-col gap-6">
                                <div className="inline-flex items-center gap-2 text-rose-400 font-bold tracking-widest text-xs uppercase">
                                    <ShieldAlert size={14} /> The Problem
                                </div>
                                <h2 className="text-3xl md:text-5xl font-black text-white leading-tight">
                                    Why do billions rely on <span className="bg-gradient-to-r from-rose-400 to-orange-500 bg-clip-text text-transparent">failing models?</span>
                                </h2>
                                <p className="text-slate-400 leading-relaxed text-base md:text-lg font-medium">
                                    Traditional Numerical Weather Prediction (NWP) models struggle with rapid atmospheric deviations. When boundary layers break, these models produce catastrophic "forecast busts"—predicting clear skies right before a devastating flash flood.
                                </p>
                                <div className="p-5 bg-slate-900/50 border border-slate-800 rounded-2xl shadow-inner mt-2">
                                    <p className="text-sm font-medium text-slate-300 italic leading-relaxed">"A single forecast bust in aviation or agriculture can cost millions of dollars and compromise public safety during critical disaster management operations."</p>
                                </div>
                            </div>

                            {/* The Solution */}
                            <div className="flex flex-col gap-6 lg:pl-10">
                                <div className="inline-flex items-center gap-2 text-indigo-400 font-bold tracking-widest text-xs uppercase">
                                    <Layers size={14} /> The Solution
                                </div>
                                <h2 className="text-3xl md:text-5xl font-black text-white leading-tight">
                                    Predicting failures using <span className="bg-gradient-to-r from-indigo-400 to-cyan-400 bg-clip-text text-transparent">Deep Learning.</span>
                                </h2>
                                <ul className="space-y-6 mt-4">
                                    {[
                                        { title: 'Continuous Satellite Sync', desc: 'Ingesting heavy telemetry from Open-Meteo & IMD across multiple spatial nodes.' },
                                        { title: 'ConvLSTM Execution', desc: 'Scanning for mathematical variance between forecasted parameters and physical reality.' },
                                        { title: 'Causal Alert Matrix', desc: 'Translating black-box neural layer outputs into understandable risk matrices for governments.' }
                                    ].map((step, i) => (
                                        <li key={i} className="flex gap-4 items-start">
                                            <div className="flex items-center justify-center w-10 h-10 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 font-black shrink-0 relative overflow-hidden shadow-inner mt-1">
                                                <span className="relative z-10">{i + 1}</span>
                                            </div>
                                            <div>
                                                <h4 className="text-white font-bold text-lg">{step.title}</h4>
                                                <p className="text-slate-400 text-sm mt-1 leading-relaxed font-medium">{step.desc}</p>
                                            </div>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="flex flex-col min-h-screen w-full bg-[#020617] text-slate-300 font-sans selection:bg-indigo-500/30 relative">
            {/* Ambient Background Glows */}
            <div className="fixed top-[-20%] left-[-10%] w-[50%] h-[50%] bg-indigo-600/10 blur-[120px] rounded-full pointer-events-none"></div>
            <div className="fixed bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-blue-600/10 blur-[120px] rounded-full pointer-events-none"></div>

            {/* Header / Nav */}
            <header className="h-24 sticky top-0 flex items-center justify-between px-4 lg:px-12 bg-slate-900/60 backdrop-blur-xl border-b border-slate-800/80 shrink-0 relative z-[200]">
                <div className="flex items-center gap-6 lg:gap-8">
                    <div className="flex items-center gap-3 cursor-pointer" onClick={() => setShowDashboard(false)}>
                        <div className="p-0.5 bg-white rounded-xl shadow-lg shadow-indigo-500/20 overflow-hidden flex items-center justify-center w-10 h-10 shrink-0 border border-indigo-500/30">
                            <img src="/logos/images (2).jpg" alt="AeroBust Logo" className="w-full h-full object-contain mix-blend-multiply" />
                        </div>
                        <span className="hidden md:block text-xl font-black bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent tracking-widest uppercase">
                            AeroBust
                        </span>
                    </div>
                    <div className="hidden md:block w-px h-8 bg-slate-700/50"></div>
                    <div className="hidden sm:block">
                        <h1 className="text-lg lg:text-xl font-bold text-white tracking-tight">Global Atmospheric Intelligence</h1>
                        <div className="flex items-center gap-3 mt-1">
                            <span className="text-[9px] lg:text-[10px] font-bold text-amber-500/80 tracking-widest uppercase">Dept. of Disaster Management</span>
                            <span className="text-[9px] px-2 py-0.5 rounded border border-slate-700 bg-slate-800 text-slate-400 font-mono">GOVT. OF INDIA</span>
                        </div>
                    </div>
                </div>

                <div className="flex items-center gap-4 lg:gap-6">
                    {/* Horizontal Tabs - Now mobile friendly */}
                    <div className="flex items-center gap-1 md:gap-2 mr-2 md:mr-4 bg-slate-900/50 p-1 md:p-1.5 rounded-2xl border border-slate-800 overflow-x-auto scrollbar-hide max-w-[170px] sm:max-w-none">
                        {['map', 'analytics', 'models'].map(item => (
                            <button
                                key={item}
                                onClick={() => setActiveTab(item)}
                                className={clsx(
                                    "text-[9px] md:text-[10px] font-bold tracking-widest uppercase px-3 py-2 md:px-4 rounded-xl transition-all whitespace-nowrap",
                                    activeTab === item ? "bg-indigo-500/20 text-indigo-300 shadow-sm" : "text-slate-500 hover:text-slate-300"
                                )}
                            >
                                {item}
                            </button>
                        ))}
                    </div>
                    {/* Govt Official Logo / Badge */}
                    <div className="hidden sm:flex items-center gap-2 bg-gradient-to-r from-amber-900/40 to-slate-900 px-4 py-2 lg:px-5 lg:py-2.5 rounded-2xl border border-amber-700/50 shadow-[0_0_15px_rgba(217,119,6,0.15)] group hover:border-amber-500/80 transition-colors">
                        <div className="flex items-center justify-center w-7 h-8 shrink-0">
                            <img src="/logos/Emblem_of_India_with_transparent_background.png" alt="Govt Emblem" className="w-full h-full object-contain drop-shadow-[0_0_8px_rgba(251,191,36,0.3)] brightness-125" />
                        </div>
                        <div className="flex flex-col ml-1">
                            <span className="text-[10px] font-black tracking-[0.2em] text-amber-500 uppercase leading-none mb-1 group-hover:text-amber-400 transition-colors">NDMA</span>
                            <span className="text-[7px] font-bold tracking-widest text-slate-400 uppercase leading-none">Authorized Node</span>
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content Area */}
            <main className="flex-1 w-full mx-auto relative z-10 flex flex-col">

                {/* Dashboard Layout Grid */}
                <div className="flex-1 w-full p-4 lg:p-8 relative z-10">
                    <div className="flex flex-col gap-8 max-w-[1600px] mx-auto w-full pb-32">

                        {activeTab === 'map' && (
                            <>
                                {/* Top: Massive Map Engine */}
                                <div className={clsx(
                                    "w-full flex-col flex transition-all duration-[400ms] shadow-2xl relative",
                                    isMapFullscreen ? "fixed inset-2 md:inset-6 z-[9999] bg-[#020617] rounded-[2rem] border-2 border-indigo-500/30 overflow-hidden" : "shrink-0 h-[50vh] min-h-[400px]"
                                )}>

                                    {/* The Map itself */}
                                    <div className="flex-1 rounded-[2rem] overflow-hidden border border-slate-700/50 relative shadow-[0_0_40px_rgba(0,0,0,0.3)] bg-slate-900/50 ring-1 ring-white/5 z-0">
                                        {isLoading && (
                                            <div className="absolute inset-0 z-50 bg-[#020617]/80 backdrop-blur-md flex items-center justify-center">
                                                <div className="flex flex-col items-center gap-5">
                                                    <div className="w-16 h-16 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin glow-spin"></div>
                                                    <p className="text-indigo-400 font-mono text-sm font-bold tracking-widest uppercase animate-pulse">Syncing Satellites...</p>
                                                </div>
                                            </div>
                                        )}
                                        <MapContainer
                                            center={[22.5937, 78.9629]}
                                            zoom={4.5}
                                            minZoom={4.5}
                                            maxZoom={10}
                                            zoomSnap={0.5}
                                            maxBounds={[
                                                [6.5, 68.0], // South-West India
                                                [35.5, 97.5] // North-East India
                                            ]}
                                            maxBoundsViscosity={1.0}
                                            className="w-full h-full z-0 bg-[#020617]"
                                            zoomControl={true}
                                        >
                                            {/* Standard OpenStreetMap with CSS filter trick to cast into Dark Mode! */}
                                            <TileLayer
                                                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                                                className="map-tiles"
                                            />

                                            {/* Dynamic Telemetry Sensor Nodes */}
                                            {regionsData.map((region) => {
                                                const hexColor = getColor(region.errorProb);
                                                const isHighRisk = region.errorProb > 40;
                                                const isCritical = region.errorProb > 70;

                                                // Advanced Futuristic UI for map markers
                                                const sensorIcon = L.divIcon({
                                                    html: `
                                                        <div class="relative flex items-center justify-center w-full h-full group">
                                                            ${isHighRisk ? `<div class="absolute inset-0 rounded-full animate-ping opacity-[0.4]" style="background-color: ${hexColor}"></div>` : ''}
                                                            ${isCritical ? `<div class="absolute inset-0 rounded-full animate-spin opacity-60 border-2 border-dashed" style="border-color: ${hexColor}; animation-duration: 4s;"></div>` : ''}
                                                            <div class="absolute inset-[3px] rounded-full border opacity-50 transition-transform duration-500 group-hover:scale-150 group-hover:opacity-100" style="border-color: ${hexColor}; background-color: ${hexColor}30;"></div>
                                                            <div class="relative w-2.5 h-2.5 rounded-full z-10" style="background-color: ${hexColor}; box-shadow: 0 0 12px 3px ${hexColor};"></div>
                                                        </div>
                                                    `,
                                                    className: 'custom-sensor-node',
                                                    iconSize: [32, 32],
                                                    iconAnchor: [16, 16]
                                                });

                                                return (
                                                    <Marker
                                                        key={region.id}
                                                        position={[region.lat, region.lng]}
                                                        icon={sensorIcon}
                                                        zIndexOffset={isCritical ? 1000 : (isHighRisk ? 500 : 0)}
                                                    >
                                                        <Tooltip className="!bg-[#0a0e17] !backdrop-blur-xl !border !border-slate-700 !text-slate-200 !shadow-2xl !rounded-2xl p-0 font-sans !opacity-100 !font-medium" direction="top" offset={[0, -10]}>
                                                            <div className="min-w-[200px] p-4 text-xs font-sans border-t-4 rounded-t-2xl" style={{ borderColor: hexColor }}>
                                                                <h4 className="font-bold text-lg text-white mb-3 pb-3 border-b border-slate-700/50 flex items-center justify-between">
                                                                    {region.name}
                                                                    <span className="text-[10px] px-2 py-0.5 bg-slate-800 rounded text-slate-400 font-mono">NODE:{region.id}</span>
                                                                </h4>
                                                                <div className="space-y-4">
                                                                    <div className="flex justify-between items-center">
                                                                        <span className="text-[10px] font-bold text-slate-500 tracking-widest uppercase">Error Prob</span>
                                                                        <span className="text-sm font-black tracking-wide" style={{ color: hexColor }}>{region.errorProb}%</span>
                                                                    </div>
                                                                    <div className="flex justify-between items-center pb-3 border-b border-slate-800/80">
                                                                        <span className="text-[10px] font-bold text-slate-500 tracking-widest uppercase">Confidence</span>
                                                                        <span className="text-sm font-black tracking-wide text-white">{region.confidence}%</span>
                                                                    </div>
                                                                    <div className="pt-1">
                                                                        <div className="grid grid-cols-2 gap-3 text-xs text-center">
                                                                            <div className="bg-slate-800/40 p-2.5 rounded-xl border border-slate-700/40 hover:bg-slate-800/80 transition-colors">
                                                                                <span className="text-slate-500 block mb-1 text-[10px] font-bold uppercase tracking-wider">Model NWP</span>
                                                                                <span className="text-white font-mono font-bold">{region.modelRain}mm</span>
                                                                            </div>
                                                                            <div className="bg-slate-800/40 p-2.5 rounded-xl border border-slate-700/40 hover:bg-slate-800/80 transition-colors">
                                                                                <span className="text-slate-500 block mb-1 text-[10px] font-bold uppercase tracking-wider">Actual</span>
                                                                                <span className="text-white font-mono font-bold">{region.expectedRain}mm</span>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </Tooltip>
                                                    </Marker>
                                                );
                                            })}
                                        </MapContainer>

                                    </div>
                                </div>

                                {/* Lead Time Scrubber Interface (MOVED BELOW MAP) */}
                                <div className="w-full max-w-4xl mx-auto transition-transform hover:-translate-y-1 duration-300 z-[50]">
                                    <div className="bg-slate-900/50 backdrop-blur-2xl p-6 rounded-[2rem] border border-slate-700/60 shadow-lg relative overflow-hidden">
                                        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-[40px] pointer-events-none"></div>
                                        <div className="flex justify-between items-end mb-5 relative z-10">
                                            <div>
                                                <h3 className="text-white font-bold tracking-wider flex items-center gap-2 text-sm"><Calendar size={18} className="text-indigo-400" /> TEMPORAL PROJECTION</h3>
                                                <p className="text-[11px] text-slate-400 mt-1 font-medium max-w-[300px]">Drag slider to analyze future NN anomaly models traversing across the region.</p>
                                            </div>
                                            <div className="bg-gradient-to-r from-indigo-500 to-blue-600 p-[1px] rounded-xl shadow-[0_0_15px_rgba(99,102,241,0.3)]">
                                                <div className="bg-[#0b1120] px-6 py-2 rounded-[11px]">
                                                    <span className="text-indigo-400 font-mono font-bold text-sm tracking-widest">DAY 0{leadTime}</span>
                                                </div>
                                            </div>
                                        </div>

                                        {/* SCIFI INTERACTIVE SEGMENTED TIMELINE TRACK */}
                                        <div className="relative flex items-stretch justify-between z-10 w-full mt-6 mb-2 gap-1.5 md:gap-2 h-12 md:h-14 bg-[#050810] p-2 rounded-2xl border border-slate-800/80 shadow-inner">
                                            {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((day) => {
                                                const isActive = parseInt(leadTime) === day;
                                                const isPast = day < parseInt(leadTime);

                                                return (
                                                    <div
                                                        key={day}
                                                        onClick={() => setLeadTime(day)}
                                                        className={clsx(
                                                            "relative cursor-pointer transform -skew-x-[12deg] overflow-hidden border-2 transition-all duration-300 group rounded-md",
                                                            isActive ? "border-indigo-500 bg-indigo-500/20 shadow-[0_0_20px_rgba(99,102,241,0.5)] flex-[1.5] z-20" :
                                                                isPast ? "border-indigo-900/40 bg-indigo-900/20 hover:bg-indigo-800/40 flex-1 z-10" : "border-slate-800/50 bg-slate-800/20 hover:bg-slate-700/50 flex-1 z-0"
                                                        )}
                                                    >
                                                        {isActive && (
                                                            <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/40 to-cyan-400/40 animate-pulse"></div>
                                                        )}
                                                        <div className={clsx(
                                                            "absolute inset-0 flex items-center justify-center skew-x-[12deg] font-black text-[9px] md:text-[11px] transition-colors tracking-wider",
                                                            isActive ? "text-white" : isPast ? "text-indigo-400/60" : "text-slate-500 group-hover:text-slate-300"
                                                        )}>
                                                            T+{day}
                                                        </div>
                                                    </div>
                                                )
                                            })}
                                        </div>

                                        <div className="flex justify-between text-[9px] uppercase font-bold text-slate-500 mt-2 px-3 tracking-[0.2em] relative z-10">
                                            <span className="text-indigo-400/70">Current Baseline</span>
                                            <span className="text-slate-600 hidden md:inline-block">Temporal Prediction Horizon</span>
                                            <span className="text-slate-500">Max Node Range</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Bottom: AI Intelligence Panel Grid */}
                                <div className="w-full grid grid-cols-1 xl:grid-cols-3 gap-6 relative z-[100]">

                                    {/* Left Column: Alerts & Matrix */}
                                    <div className="flex flex-col gap-5 xl:col-span-1">

                                        {/* Dynamic Alert Protocol */}
                                        {(() => {
                                            const highestRiskRegion = [...regionsData].sort((a, b) => b.errorProb - a.errorProb)[0];
                                            if (highestRiskRegion && highestRiskRegion.errorProb > 50) {
                                                return (
                                                    <div className="grid transition-all">
                                                        <div className="p-0.5 rounded-[2rem] bg-gradient-to-b from-red-500/50 to-transparent shadow-[0_0_30px_rgba(239,68,68,0.15)] shrink-0 active-glow">
                                                            <div className="bg-[#150a0d] p-6 rounded-[2rem] relative overflow-hidden group">
                                                                <div className="absolute top-0 right-0 w-64 h-64 bg-red-500/10 rounded-full blur-[60px] group-hover:bg-red-500/20 transition-all duration-700"></div>
                                                                <div className="flex gap-5 items-start relative z-10">
                                                                    <div className="bg-gradient-to-b from-red-500/20 to-red-900/20 p-3.5 rounded-2xl text-red-500 border border-red-500/30 shrink-0 shadow-inner">
                                                                        <ShieldAlert size={28} strokeWidth={2.5} />
                                                                    </div>
                                                                    <div className="pt-0.5">
                                                                        <h3 className="font-bold text-red-400 text-[15px] tracking-wide flex items-center gap-2">
                                                                            CRITICAL BUST RISK
                                                                            <span className="flex h-2 w-2 relative ml-1">
                                                                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                                                                                <span className="relative inline-flex rounded-full h-2 w-2 bg-red-500"></span>
                                                                            </span>
                                                                        </h3>
                                                                        <p className="text-sm text-red-200/80 mt-2 leading-relaxed font-medium">
                                                                            Forecast boundary breakdown ({highestRiskRegion.errorProb}% Deviation) detected over <span className="font-bold text-white bg-red-500/20 px-2 py-0.5 rounded ml-1">{highestRiskRegion.name}</span> for Day {leadTime}.
                                                                        </p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                );
                                            } else if (highestRiskRegion) {
                                                return (
                                                    <div className="grid transition-all">
                                                        <div className="p-0.5 rounded-[2rem] bg-gradient-to-b from-emerald-500/30 to-transparent shadow-[0_0_30px_rgba(16,185,129,0.1)] shrink-0">
                                                            <div className="bg-[#0a1510] p-6 rounded-[2rem] relative overflow-hidden group">
                                                                <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-[60px] group-hover:bg-emerald-500/20 transition-all duration-700"></div>
                                                                <div className="flex gap-5 items-start relative z-10">
                                                                    <div className="bg-gradient-to-b from-emerald-500/20 to-emerald-900/20 p-3.5 rounded-2xl text-emerald-400 border border-emerald-500/30 shrink-0 shadow-inner">
                                                                        <Activity size={28} strokeWidth={2.5} />
                                                                    </div>
                                                                    <div className="pt-0.5">
                                                                        <h3 className="font-bold text-emerald-400 text-[15px] tracking-wider uppercase">Atmosphere Stable</h3>
                                                                        <p className="text-sm text-emerald-200/80 mt-2 leading-relaxed font-medium">
                                                                            All active nodes report nominal parameters. High confidence in baseline NWP models for Day {leadTime}.
                                                                        </p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                );
                                            }
                                            return null;
                                        })()}

                                        {/* Sector-wise Risk Impact Matrix */}
                                        {(() => {
                                            const highestRiskRegion = [...regionsData].sort((a, b) => b.errorProb - a.errorProb)[0];
                                            if (!highestRiskRegion) return null;

                                            const prob = highestRiskRegion.errorProb;

                                            let aviationRisk = { level: 'NOMINAL', color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/30' };
                                            let agriRisk = { level: 'NOMINAL', color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/30' };
                                            let roadRisk = { level: 'NOMINAL', color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/30' };

                                            if (prob > 70) {
                                                aviationRisk = { level: 'CRITICAL', color: 'text-red-400', bg: 'bg-red-500/10 border-red-500/30 shadow-[0_0_15px_rgba(239,68,68,0.1)]' };
                                                agriRisk = { level: 'HIGH RISK', color: 'text-orange-400', bg: 'bg-orange-500/10 border-orange-500/30' };
                                                roadRisk = { level: 'MODERATE', color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/30' };
                                            } else if (prob > 40) {
                                                aviationRisk = { level: 'MODERATE', color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/30' };
                                                agriRisk = { level: 'MODERATE', color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/30' };
                                                roadRisk = { level: 'LOW RISK', color: 'text-emerald-400', bg: 'bg-emerald-500/10 border-emerald-500/30' };
                                            }

                                            return (
                                                <div className="bg-slate-900/40 backdrop-blur-md border border-slate-700/50 p-5 rounded-[2rem] shrink-0">
                                                    <h3 className="font-bold text-white text-[13px] tracking-widest uppercase mb-4 flex items-center gap-2">
                                                        <ShieldAlert size={16} className="text-indigo-400" /> Sector Impact Matrix
                                                    </h3>
                                                    <div className="grid grid-cols-3 gap-3">
                                                        <div className={`p-3 rounded-2xl border ${aviationRisk.bg} flex flex-col items-center justify-center text-center transition-colors duration-500`}>
                                                            <span className="text-[9px] text-slate-400 font-bold uppercase tracking-widest mb-1.5 flex items-center gap-1">✈️ Aviation</span>
                                                            <span className={`text-[10px] sm:text-xs font-black tracking-wider ${aviationRisk.color}`}>{aviationRisk.level}</span>
                                                        </div>
                                                        <div className={`p-3 rounded-2xl border ${agriRisk.bg} flex flex-col items-center justify-center text-center transition-colors duration-500`}>
                                                            <span className="text-[9px] text-slate-400 font-bold uppercase tracking-widest mb-1.5 flex items-center gap-1">🌾 Agri</span>
                                                            <span className={`text-[10px] sm:text-xs font-black tracking-wider ${agriRisk.color}`}>{agriRisk.level}</span>
                                                        </div>
                                                        <div className={`p-3 rounded-2xl border ${roadRisk.bg} flex flex-col items-center justify-center text-center transition-colors duration-500`}>
                                                            <span className="text-[9px] text-slate-400 font-bold uppercase tracking-widest mb-1.5 flex items-center gap-1">🚗 Road</span>
                                                            <span className={`text-[10px] sm:text-xs font-black tracking-wider ${roadRisk.color}`}>{roadRisk.level}</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })()}
                                    </div> {/* Close Left Column (Alerts & Matrix) */}

                                    {/* Right Column: INTERACTIVE Deep Learning Insights Engine */}
                                    <div className="xl:col-span-2 bg-slate-900/30 backdrop-blur-md border border-slate-700/50 p-6 rounded-[2rem] relative overflow-hidden group transition-all shrink-0">
                                        <div className="absolute -top-32 -right-32 w-80 h-80 bg-indigo-500/10 rounded-full blur-[100px] pointer-events-none group-hover:bg-indigo-500/20 transition-all duration-700"></div>

                                        <div className="flex justify-between items-center mb-6 relative z-10">
                                            <h3 className="flex items-center gap-3 font-bold text-white text-[15px] tracking-widest uppercase mb-4 sm:mb-0">
                                                <Layers size={18} className="text-indigo-400" /> Insight Engine
                                            </h3>
                                            <div className="flex flex-wrap items-center gap-3">
                                                <button
                                                    onClick={generateReport}
                                                    className="flex items-center gap-2 px-3 py-1.5 bg-red-500/10 hover:bg-red-500/20 border border-red-500/40 text-red-400 hover:text-red-300 text-[10px] font-black uppercase tracking-widest rounded shadow-sm transition-all"
                                                >
                                                    <Download size={14} /> Export Report
                                                </button>
                                                <span className="text-[9px] font-bold tracking-[0.2em] text-indigo-300 bg-indigo-500/10 px-3 py-1.5 rounded flex gap-2 items-center border border-indigo-500/20 shadow-inner">
                                                    LIVE FEED
                                                    <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse"></div>
                                                </span>
                                            </div>
                                        </div>

                                        <div className="space-y-4 relative z-10 pr-1">
                                            {regionsData.sort((a, b) => b.errorProb - a.errorProb).map((region, idx) => {
                                                const isExpanded = expandedRegion === region.id;

                                                // Mocked Deep-dive features tied deterministically to region ID to look extremely scientific when expanded
                                                const thermalWeight = Math.abs((region.lat * 10) % 50 + 20).toFixed(1);
                                                const aeroWeight = Math.abs((region.lng * 10) % 30 + 10).toFixed(1);
                                                const hydroWeight = (100 - thermalWeight - aeroWeight).toFixed(1);

                                                return (
                                                    <div
                                                        key={region.id || idx}
                                                        onClick={() => setExpandedRegion(isExpanded ? null : region.id)}
                                                        className={clsx(
                                                            "cursor-pointer bg-[#0b0f19]/90 p-5 rounded-3xl border transition-all duration-500 relative overflow-hidden group/card shadow-lg",
                                                            isExpanded ? "border-indigo-500/50 shadow-[0_10px_40px_rgba(99,102,241,0.2)] bg-[#101726]/90" : "border-slate-700/60 hover:border-indigo-500/40 hover:shadow-[0_10px_30px_rgba(99,102,241,0.1)]"
                                                        )}
                                                    >
                                                        {/* Selection Indicator Strip */}
                                                        <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-slate-800 transition-colors duration-500 ease-in-out" style={{ backgroundColor: isExpanded ? '#6366f1' : undefined }}></div>

                                                        {/* Top Row: Region & Carat */}
                                                        <div className="flex justify-between items-center mb-4 px-2">
                                                            <div className="flex items-center gap-3">
                                                                <span className="font-bold text-lg text-slate-100 tracking-wide">{region.name}</span>
                                                                <div className={clsx("rounded-full p-1 transition-colors", isExpanded ? "bg-indigo-500/20" : "bg-slate-800")}>
                                                                    {isExpanded ? <ChevronUp size={14} className="text-indigo-400" /> : <ChevronDown size={14} className="text-slate-500" />}
                                                                </div>
                                                            </div>
                                                            <div className={clsx(
                                                                "px-3 py-1.5 rounded-xl text-xs font-black tracking-widest uppercase border backdrop-blur-md shadow-inner",
                                                                region.errorProb > 70 ? "bg-red-500/10 text-red-400 border-red-500/30" :
                                                                    region.errorProb > 40 ? "bg-amber-500/10 text-amber-400 border-amber-500/30" :
                                                                        "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                                                            )}>
                                                                {region.errorProb}% ERR
                                                            </div>
                                                        </div>

                                                        {/* Base Confidence Bar Group (Always Visible) */}
                                                        <div className="px-2">
                                                            <div className="w-full bg-slate-800/80 rounded-full h-2 mb-2 overflow-hidden border border-slate-700/50 shadow-inner">
                                                                <div
                                                                    className="h-full rounded-full transition-all duration-1000 ease-out relative"
                                                                    style={{
                                                                        width: `${region.confidence}%`,
                                                                        backgroundColor: getColor(100 - region.confidence)
                                                                    }}
                                                                >
                                                                    <div className="absolute inset-0 bg-gradient-to-r from-transparent to-white/30"></div>
                                                                </div>
                                                            </div>
                                                            <div className="flex justify-between text-[10px] font-bold tracking-widest text-slate-500 uppercase">
                                                                <span>Model Confidence</span>
                                                                <span className="text-white">{region.confidence}%</span>
                                                            </div>
                                                        </div>

                                                        {/* Expandable Deep Dive Section */}
                                                        <div className={clsx(
                                                            "grid transition-all duration-500 ease-in-out",
                                                            isExpanded ? "grid-rows-[1fr] opacity-100 mt-5" : "grid-rows-[0fr] opacity-0"
                                                        )}>
                                                            <div className="overflow-hidden">
                                                                <div className="pt-4 border-t border-slate-700/50 space-y-4">

                                                                    {/* LSTM Feature Attention Weights */}
                                                                    <div className="px-2">
                                                                        <div className="flex items-center justify-between mb-3 text-[10px] font-bold text-indigo-400 tracking-[0.2em] uppercase">
                                                                            <span className="flex items-center gap-2"><Zap size={12} /> AI Feature Attention</span>
                                                                        </div>
                                                                        <div className="grid grid-cols-3 gap-2">
                                                                            <div className="bg-[#050810] p-2.5 rounded-xl border border-rose-900/30 shadow-inner">
                                                                                <div className="flex items-center gap-1.5 text-rose-400 mb-1"><Thermometer size={12} /> <span className="text-[9px] uppercase font-bold">Thermal</span></div>
                                                                                <div className="text-white font-mono text-xs">{thermalWeight}%</div>
                                                                            </div>
                                                                            <div className="bg-[#050810] p-2.5 rounded-xl border border-cyan-900/30 shadow-inner">
                                                                                <div className="flex items-center gap-1.5 text-cyan-400 mb-1"><Wind size={12} /> <span className="text-[9px] uppercase font-bold">Aero</span></div>
                                                                                <div className="text-white font-mono text-xs">{aeroWeight}%</div>
                                                                            </div>
                                                                            <div className="bg-[#050810] p-2.5 rounded-xl border border-blue-900/30 shadow-inner">
                                                                                <div className="flex items-center gap-1.5 text-blue-400 mb-1"><Droplet size={12} /> <span className="text-[9px] uppercase font-bold">Hydro</span></div>
                                                                                <div className="text-white font-mono text-xs">{hydroWeight}%</div>
                                                                            </div>
                                                                        </div>
                                                                    </div>

                                                                    {/* ML Explainability Output */}
                                                                    <div className="bg-[#050810] p-4 rounded-2xl border border-slate-800 text-slate-300 leading-relaxed shadow-inner group-hover/card:border-slate-700 transition-colors duration-300 relative overflow-hidden">
                                                                        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-[30px] pointer-events-none"></div>
                                                                        <span className="text-indigo-500 font-bold text-[10px] uppercase tracking-[0.2em] flex items-center gap-2 mb-2 relative z-10">
                                                                            <Cpu size={12} /> Causal Output Generator
                                                                        </span>
                                                                        <p className="text-[13px] font-medium text-slate-400 relative z-10">
                                                                            {region.explainability || "Processing meteorological parameters through LSTM..."}
                                                                        </p>
                                                                    </div>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                )
                                            })}
                                        </div>
                                    </div>
                                </div>
                            </>
                        )}

                        {activeTab === 'analytics' && (
                            <div className="flex-1 rounded-[2rem] border border-slate-700/50 bg-slate-900/50 p-8 flex flex-col relative overflow-hidden shadow-xl">
                                <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-500/10 rounded-full blur-[120px] pointer-events-none"></div>
                                <h2 className="text-3xl font-black text-white mb-2 relative z-10">Risk Analytics</h2>
                                <p className="text-slate-400 mb-8 relative z-10">Pan-India Neural Net Model Evaluation</p>

                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative z-10">
                                    <div className="bg-slate-800/40 p-6 rounded-3xl border border-slate-700/50">
                                        <h4 className="text-slate-500 text-xs font-bold uppercase tracking-widest mb-2">Total Monitored Nodes</h4>
                                        <div className="text-4xl font-black text-white">{regionsData.length || 57}</div>
                                    </div>
                                    <div className="bg-slate-800/40 p-6 rounded-3xl border border-slate-700/50">
                                        <h4 className="text-slate-500 text-xs font-bold uppercase tracking-widest mb-2">System Average Confidence</h4>
                                        <div className="text-4xl font-black text-emerald-400">82.4%</div>
                                    </div>
                                    <div className="bg-red-500/10 p-6 rounded-3xl border border-red-500/20">
                                        <h4 className="text-red-400/80 text-xs font-bold uppercase tracking-widest mb-2">High Risk Zones</h4>
                                        <div className="text-4xl font-black text-red-500">{regionsData.filter(r => r.errorProb > 60).length} Regions</div>
                                    </div>
                                </div>

                                <div className="mt-8 bg-slate-800/40 border border-slate-700/30 rounded-3xl h-64 flex items-center justify-center relative flex-col">
                                    <Activity size={48} className="text-slate-600 mb-4" />
                                    <p className="text-slate-400 font-bold">Chart Module Initializing (Beta Feature)</p>
                                </div>
                            </div>
                        )}

                        {activeTab === 'models' && (
                            <div className="flex-1 rounded-[2rem] border border-slate-700/50 bg-slate-900/50 p-8 flex flex-col relative overflow-hidden shadow-xl">
                                <h2 className="text-3xl font-black text-white mb-2 relative z-10">Model Layers Pipeline</h2>
                                <p className="text-slate-400 mb-8 relative z-10">TabularBustLSTM Model Architecture</p>

                                <div className="space-y-4">
                                    <div className="bg-slate-800/40 p-4 rounded-xl border border-slate-700/50 flex justify-between items-center">
                                        <div className="font-mono text-sm text-indigo-300">nn.LSTM(input_size=3, hidden=32)</div>
                                        <span className="text-xs text-slate-500 bg-slate-900 px-3 py-1 rounded">Active</span>
                                    </div>
                                    <div className="bg-slate-800/40 p-4 rounded-xl border border-slate-700/50 flex justify-between items-center">
                                        <div className="font-mono text-sm text-indigo-300">nn.Linear(32, 1) -&gt; Output Stage</div>
                                        <span className="text-xs text-slate-500 bg-slate-900 px-3 py-1 rounded">Active</span>
                                    </div>
                                    <div className="bg-slate-800/40 p-4 rounded-xl border border-slate-700/50 flex justify-between items-center">
                                        <div className="font-mono text-sm text-emerald-300">nn.Sigmoid() * 100 -&gt; Probabilty %</div>
                                        <span className="text-xs text-slate-500 bg-slate-900 px-3 py-1 rounded">Active</span>
                                    </div>
                                </div>
                            </div>
                        )}

                        {activeTab === 'settings' && (
                            <div className="flex-1 rounded-[2rem] border border-slate-700/50 bg-slate-900/50 p-8 flex flex-col relative overflow-hidden shadow-xl">
                                <h2 className="text-3xl font-black text-white mb-2 relative z-10">Preferences</h2>
                                <p className="text-slate-400 mb-8 relative z-10">System configurations</p>
                                <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 rounded-xl">
                                    Enterprise Configurations are locked on this prototype instance.
                                </div>
                            </div>
                        )}

                    </div>
                </div>
            </main>

            {/* Custom Global Scrollbar CSS injection */}
            <style jsx global>{`
                .leaflet-tile {
                    filter: invert(100%) hue-rotate(180deg) brightness(0.85) contrast(1.2) saturate(0.5);
                }
                .scrollbar-hide::-webkit-scrollbar {
                    display: none;
                }
                .scrollbar-hide {
                    -ms-overflow-style: none;
                    scrollbar-width: none;
                }
                @keyframes shimmer {
                    100% { transform: translateX(100%); }
                }
                @keyframes fadeInUp {
                    from { opacity: 0; transform: translateY(20px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                .animate-fade-in-up {
                    animation: fadeInUp 0.8s ease-out forwards;
                }
                input[type=range]::-webkit-slider-thumb {
                    appearance: none;
                    width: 20px;
                    height: 20px;
                    background: #fff;
                    border: 3px solid #6366f1;
                    border-radius: 50%;
                    cursor: pointer;
                    box-shadow: 0 0 15px rgba(99,102,241,0.5);
                    transition: transform 0.2s;
                }
                input[type=range]::-webkit-slider-thumb:hover {
                    transform: scale(1.2);
                }
            `}</style>
        </div>
    );
}
